# Site settings
title: KCErb
email: iamkcerb@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is KC Erb's homepage for hosting projects, and an online resume / CV.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kcerb.com" # the base hostname & protocol for your site
github_username:  KCErb

# Build settings
markdown: kramdown

# Timeago settings
jekyll_timeago:
  depth: 1 
